// <auto-generated />
using System;
using EventTicketSystem.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventTicketSystem.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523084640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventTicketSystem.Web.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Music",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An electrifying night of rock music featuring top bands from around the world.",
                            EndDate = new DateTime(2026, 7, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            StartDate = new DateTime(2026, 7, 15, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Rock Music Festival 2026",
                            Venue = "Central Park Amphitheater, New York"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Technology",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Explore the latest innovations in AI, cloud computing, and software development.",
                            EndDate = new DateTime(2026, 8, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            StartDate = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Tech Conference 2026",
                            Venue = "Convention Center, San Francisco"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Comedy",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laugh out loud with the best stand-up comedians performing live.",
                            EndDate = new DateTime(2026, 6, 10, 22, 30, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            StartDate = new DateTime(2026, 6, 10, 20, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Stand-Up Comedy Night",
                            Venue = "Comedy Club Downtown, Chicago"
                        });
                });

            modelBuilder.Entity("EventTicketSystem.Web.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EventTicketSystem.Web.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EventTicketSystem.Web.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Standing area access",
                            EventId = 1,
                            Name = "General Admission",
                            Price = 49.99m,
                            SoldQuantity = 0,
                            TotalQuantity = 500
                        },
                        new
                        {
                            Id = 2,
                            Description = "Front section seating + backstage pass",
                            EventId = 1,
                            Name = "VIP",
                            Price = 149.99m,
                            SoldQuantity = 0,
                            TotalQuantity = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Full conference access",
                            EventId = 2,
                            Name = "Standard",
                            Price = 299.00m,
                            SoldQuantity = 0,
                            TotalQuantity = 300
                        },
                        new
                        {
                            Id = 4,
                            Description = "Conference + all workshop sessions",
                            EventId = 2,
                            Name = "Workshop Pass",
                            Price = 499.00m,
                            SoldQuantity = 0,
                            TotalQuantity = 50
                        },
                        new
                        {
                            Id = 5,
                            Description = "Standard seating",
                            EventId = 3,
                            Name = "Regular",
                            Price = 25.00m,
                            SoldQuantity = 0,
                            TotalQuantity = 200
                        },
                        new
                        {
                            Id = 6,
                            Description = "Front row seating + meet & greet",
                            EventId = 3,
                            Name = "Premium",
                            Price = 75.00m,
                            SoldQuantity = 0,
                            TotalQuantity = 30
                        });
                });

            modelBuilder.Entity("EventTicketSystem.Web.Models.OrderItem", b =>
                {
                    b.HasOne("EventTicketSystem.Web.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTicketSystem.Web.Models.TicketType", "TicketType")
                        .WithMany("OrderItems")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("EventTicketSystem.Web.Models.TicketType", b =>
                {
                    b.HasOne("EventTicketSystem.Web.Models.Event", "Event")
                        .WithMany("TicketTypes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventTicketSystem.Web.Models.Event", b =>
                {
                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("EventTicketSystem.Web.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EventTicketSystem.Web.Models.TicketType", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
